name: Build/Test CI

on:
  push:
    branches:
      - master
      - "release/*"
  pull_request:
    branches:
      - master
      - "release/*"

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Run tests
        run: npm run test:ci
      - name: Run examples
        run: ./test_examples.sh
